gha: Increase Ingress status wait time
The current value is set as 10s, which might not be enough for a small
kind cluster in CI environment, hence timeout happened as per below.

This commit is to increase max wait time to 60s to mitigate the issue.

```
  Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:181
    Then The Ingress status shows the IP address or FQDN where it is exposed # features/path_rules.feature:93
      Error: waiting for ingress status update: timed out waiting for the condition
```

Fixes: #25040
Signed-off-by: Tam Mach <tam.mach@cilium.io>